development:
   adapter: mysql2
   database: pos
   username: root
   password: root
   host: localhost

test:
   adapter: mysql2
   database: pos
   username: root
   password: root
   host: localhost

production:
   adapter: mysql2
   database: mintifi
   username: root
   password: root
   host: 54.209.104.52
