development:
   adapter: mysql2
   database: pos
   username: root
   password: root
   host: localhost

test:
   adapter: mysql2
   database: pos
   username: root
   password: root
   host: localhost

production:
   adapter: mysql2
   database: pos
   username: root
   password: root
   host: localhost
